apiVersion: v1
kind: Service
metadata:
  name: flask-svc
spec:
  selector:
    app: flask-deploy
  ports:
  - protocol: TCP
    port: 80  # Service의 포트
    targetPort: 8080  # 컨테이너가 노출하는 포트
    nodePort: 30080
  type: NodePort  
