apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql-deploy
  ports:
  - protocol: TCP
    port: 3306  # Service의 포트
    targetPort: 3306  # 컨테이너가 노출하는 포트
    nodePort: 30306
  type: NodePort  
